sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

  alioss:
    endpoint: "https://oss-cn-beijing.aliyuncs.com"
    region: "cn-beijing"
    bucket-name: "javaweb-zhou"

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wx349c400d51cc50fa
    secret: c56c7752cbfadb74bbb5c53abe289fe4
